USE `computer-database-db`;

insert into company (id,name) values (  1,'Apple Inc.');
insert into company (id,name) values (  2,'Thinking Machines');
insert into company (id,name) values (  3,'RCA');
insert into company (id,name) values (  4,'Netronics');
insert into company (id,name) values (  5,'Tandy Corporation');
insert into company (id,name) values (  6,'Commodore International');
insert into company (id,name) values (  7,'MOS Technology');
insert into company (id,name) values (  8,'Micro Instrumentation and Telemetry Systems');
insert into company (id,name) values (  9,'IMS Associates, Inc.');
insert into company (id,name) values ( 10,'Digital Equipment Corporation');
insert into company (id,name) values ( 11,'Lincoln Laboratory');
insert into company (id,name) values ( 12,'Moore School of Electrical Engineering');
insert into company (id,name) values ( 13,'IBM');
insert into company (id,name) values ( 14,'Amiga Corporation');
insert into company (id,name) values ( 15,'Canon');
insert into company (id,name) values ( 16,'Nokia');
insert into company (id,name) values ( 17,'Sony');
insert into company (id,name) values ( 18,'OQO');
insert into company (id,name) values ( 19,'NeXT');    
insert into company (id,name) values ( 20,'Atari');
insert into company (id,name) values ( 22,'Acorn computer');
insert into company (id,name) values ( 23,'Timex Sinclair');
insert into company (id,name) values ( 24,'Nintendo');
insert into company (id,name) values ( 25,'Sinclair Research Ltd');
insert into company (id,name) values ( 26,'Xerox');
insert into company (id,name) values ( 27,'Hewlett-Packard');
insert into company (id,name) values ( 28,'Zemmix');
insert into company (id,name) values ( 29,'ACVS');
insert into company (id,name) values ( 30,'Sanyo');
insert into company (id,name) values ( 31,'Cray');
insert into company (id,name) values ( 32,'Evans & Sutherland');    
insert into company (id,name) values ( 33,'E.S.R. Inc.');
insert into company (id,name) values ( 34,'OMRON');
insert into company (id,name) values ( 35,'BBN Technologies');
insert into company (id,name) values ( 36,'Lenovo Group');
insert into company (id,name) values ( 37,'ASUS');
insert into company (id,name) values ( 38,'Amstrad');
insert into company (id,name) values ( 39,'Sun Microsystems');
insert into company (id,name) values ( 40,'Texas Instruments');
insert into company (id,name) values ( 41,'HTC Corporation');
insert into company (id,name) values ( 42,'Research In Motion');
insert into company (id,name) values ( 43,'Samsung Electronics');

insert into computer (id,name,introduced,discontinued,company_id) values (  1,'MacBook Pro 15.4 inch',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  2,'CM-2a',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  3,'CM-200',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  4,'CM-5e',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  5,'CM-5','1991-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  6,'MacBook Pro','2006-01-10',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  7,'Apple IIe',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (  8,'Apple IIc',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (  9,'Apple IIGS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 10,'Apple IIc Plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 11,'Apple II Plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 12,'Apple III','1980-05-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 13,'Apple Lisa',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 14,'CM-2',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( 15,'Connection Machine','1987-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( 16,'Apple II','1977-04-01','1993-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 17,'Apple III Plus','1983-12-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 18,'COSMAC ELF',null,null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( 19,'COSMAC VIP','1977-01-01',null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( 20,'ELF II','1977-01-01',null,4);
insert into computer (id,name,introduced,discontinued,company_id) values ( 21,'Macintosh','1984-01-24',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 22,'Macintosh II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 23,'Macintosh Plus','1986-01-16','1990-10-15',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 24,'Macintosh IIfx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 25,'iMac','1998-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 26,'Mac Mini','2005-01-22',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 27,'Mac Pro','2006-08-07',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 28,'Power Macintosh','1994-03-01','2006-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 29,'PowerBook','1991-01-01','2006-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 30,'Xserve',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 31,'Powerbook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 32,'Powerbook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 33,'Powerbook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 34,'PowerBook Duo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 35,'PowerBook 190',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 36,'Macintosh Quadra','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 37,'Macintosh Quadra 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 38,'Macintosh Quadra 700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 39,'Macintosh LC','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 40,'Macintosh LC II','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 41,'Macintosh LC III','1993-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 42,'Macintosh LC III+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 43,'Macintosh Quadra 605','1993-10-21',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 44,'Macintosh LC 500 series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 45,'TRS-80 Color Computer','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values ( 46,'Acorn System 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 47,'Dragon 32/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 48,'MEK6800D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 49,'Newbear 77/68',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 50,'Commodore PET',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 51,'Commodore 64','1982-08-01','1994-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 52,'Commodore 64C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 53,'Commodore SX-64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 54,'Commodore 128',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 55,'Apple I','1976-04-01','1977-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 56,'KIM-1','1975-01-01',null,7);
insert into computer (id,name,introduced,discontinued,company_id) values ( 57,'Altair 8800','1974-12-19',null,8);
insert into computer (id,name,introduced,discontinued,company_id) values ( 58,'IMSAI 8080','1975-08-01',null,9);
insert into computer (id,name,introduced,discontinued,company_id) values ( 59,'IMSAI Series Two',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 60,'VAX','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( 61,'VAX 11/780','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( 62,'VAX 11/750','1980-10-01',null,10);

insert into computer (id,name,introduced,discontinued,company_id) values (507,'English Electric DEUCE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (508,'CER-203',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (509,'CER-22',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (510,'Kentucky Linux Athlon Testbed',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (511,'QNAP TS-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (512,'iPad','2010-01-01','2011-03-02',1);
insert into computer (id,name,introduced,discontinued,company_id) values (513,'iPhone 2G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (514,'Inslaw',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (515,'WePad','2010-07-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (516,'MacBook Parts',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (517,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240LL/A) DDR2 Model',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (518,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240T/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (519,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240X/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (520,'MacBook 13-inch Core 2 Duo 2.26GHz (Unibody MC207LL/A) DDR3 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (521,'MC240LL/A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (522,'D.K.COMMUNICATION',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (523,'iPhone 4',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (524,'Nintendo 3DS','2010-03-23',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (525,'ASUS Eee PC 1005PE','2010-01-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (526,'National Law Enforcement System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (527,'BlackBerry PlayBook',null,null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (528,'Barnes & Noble nook','2009-10-20',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (529,'SAM Coupé',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (530,'HTC Dream','2008-10-22',null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (531,'Samsung Galaxy Tab','2010-09-02',null,43);
insert into computer (id,name,introduced,discontinued,company_id) values (532,'BlackBerry PlayBook','2010-09-27',null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (533,'Tianhe-I',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (534,'Kno',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (535,'ThinkPad 701 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (536,'ThinkPad 340 CSE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (537,'ThinkPad 755 CX',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (538,'ThinkPad 755 CE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (539,'ThinkPad 370 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (540,'Coleco Adam','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (541,'Nebulae',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (542,'Alex eReader',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (543,'Acer Iconia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (544,'Archos 101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (545,'Fujitsu Lifebook T900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (546,'Motorola Xoom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (547,'ViewSonic G Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (548,'DEC Professional','1982-01-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (549,'DEC Multia','1994-11-07',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (550,'DEC Firefly',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (551,'DEC 3000 AXP',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (552,'DEC 2000 AXP','1993-05-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (553,'DEC 4000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (554,'DEC 7000/10000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (555,'DEC Professional 350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (556,'DEC Rainbow 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (557,'DEC Professional 325',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (558,'DECmate II',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (559,'DECmate',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (560,'DECsystem',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (561,'NetApp Filer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (562,'DEC GT40',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (563,'ecoATM',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (564,'MindWave BrainCubed Education Bundle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (565,'PalmPilot',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (566,'Upcoming iPhone 5',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (567,'Dell Inspiron 560 Desktop Computer ',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (568,'IPad 2',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (569,'HP TouchPad','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (570,'HP Veer','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (571,'Lenovo Thinkpad Edge 11',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (572,'Dell Vostro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (573,'Gateway LT3103U','2008-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (574,'iPhone 4S','2011-10-14',null,1);
