  dind:
    container_name: dind
    image: jpetazzo/dind
    expose:
      - 4242
    environment:
      PORT: 4242
    privileged: true

  mysql:
    container_name: mysql
    image: ccedric/cdb-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  glazer:
    container_name: glazer
    image: clementgayvallet/glazer-container-agent
    links:
      - dind

  webapp:
    container_name: webapp
    image: ccedric/cdb-webapp
    links:
      - mysql
    ports:
      - 8888:8080

  jenkins:
    container_name: jenkins
    image: ccedric/jenkins:latest
    links:
      - dind
      - webapp
    ports:
      - 8080:8080
