version: '2'

services:
  dind:
    container_name: dind
    image: jpetazzo/dind
    expose:
      - 4242
    environment:
      PORT: 4242
    privileged: true

  glazer:
    container_name: glazer
    image: clementgayvallet/glazer-container-agent
    links:
      - dind

  webapp:
    container_name: webapp
    image: ccedric/cdb-webapp
    ports:
      - 8888:8080

  jenkins:
    container_name: jenkins
    image: ccedric/jenkins:latest
    links:
      - dind
      - webapp
    ports:
      - 8080:8080
    volumes:
      - .dockercfg:/root/.dockercfg
